name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Install dependencies
      run: sudo apt-get install apksigner
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build release app
      run: |
          ./gradlew assembleRelease
          # jarsigner -verbose -keystore ~/.config/.android/debug.keystore -storepass android -keypass android app/build/outputs/apk/release/app-release-unsigned.apk androiddebugkey
          # apksigner sign --ks ~/.config/.android/debug.keystore --ks-key-alias androiddebugkey --ks-pass pass:android app/build/outputs/apk/release/app-release-unsigned.apk
          # mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk
    - name: Sort files
      run: |
          mkdir output
          mv app/build/outputs/apk/release/app-release*.apk output
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: release.zip
        path: output/app-release*.*
        if-no-files-found: error
